### ISSUE TITLE
Support for subaccounts/program name

### ISSUE THREAD

**Issue by quazzuk** [crypto-chassis/ccapi#115]
**Describe the bug**
rest_execution_management_simple doesn't appear to support subaccounts/program name despite the usage message indicating it does i.e. `"Usage: <program name> get_open_orders <symbol>`

**To Reproduce**
1. build examples
2. attempt to run `rest_execution_management_simple` example as usage suggests i.e. `main get_open_orders BTCUSD`

**Expected behavior**

Correct subaccount is passed to the api, in my case FTX. Instead I get either "Please provide the first command line argument from this list:" if passing the subaccount or if I leave out, then I get an error message from the api indicating I only have permissions for subaccount "foo".

It looks like the Request object doesn't support subaccounts.

**Comment by quazzuk** [comment]
From grepping the source it looks like I can set `#CCAPI_FTX_API_SUBACCOUNT` however I'm still having trouble getting it to work...

**Comment by quazzuk** [comment]
looks like adding 

```auto apiSubaccountName = mapGetWithDefault(credential, this->apiSubaccountName);
    req.set("FTX-SUBACCOUNT", apiSubaccountName)```

to `convertReq` fixes the issue but really the example needs updating to reflect this.

Do you want a PR?

**Comment by cryptochassis** [comment]
> looks like adding
> 
> `auto apiSubaccountName = mapGetWithDefault(credential, this->apiSubaccountName);`
> `req.set("FTX-SUBACCOUNT", apiSubaccountName)`
> 
> to `convertReq` fixes the issue but really the example needs updating to reflect this.
> 
> Do you want a PR?

Sure. Thank you.
