### ISSUE TITLE
Decimal doesn't correctly handle negative numbers

### ISSUE THREAD

**Issue by quazzuk** [crypto-chassis/ccapi#126]
**Describe the bug**
`stoul` fails in Decimal constructor for negative numbers.

**To Reproduce**
1. construct a Decimal from `Decimal{"-0.001"}`

**Expected behavior**
1. Correctly handles negative numbers

I think the issue is [here](https://github.com/crypto-chassis/ccapi/blob/76cd2d4b105cdcea08e29f5337c30bc8f6f99988/include/ccapi_cpp/ccapi_decimal.h#L17)
I think it should be `fixedPointValue.erase(0, 1);`

**Comment by quazzuk** [comment]
On this topic, have you explored using `boost/multiprecision/cpp_dec_float.hpp`. I understand the current implementation is nice and minimalist, but ultimately I find I need to do some computation on the prices/sizes and currently that means converting to floating point.

**Comment by cryptochassis** [comment]
> **Describe the bug**
> `stoul` fails in Decimal constructor for negative numbers.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. construct a Decimal from `Decimal{"-0.001"}`
> 
> **Expected behavior**
> 
> 1. Correctly handles negative numbers
> 
> I think the issue is [here](https://github.com/crypto-chassis/ccapi/blob/76cd2d4b105cdcea08e29f5337c30bc8f6f99988/include/ccapi_cpp/ccapi_decimal.h#L17)
> I think it should be `fixedPointValue.erase(0, 1);`

You are definitely right.

**Comment by cryptochassis** [comment]
> On this topic, have you explored using `boost/multiprecision/cpp_dec_float.hpp`. I understand the current implementation is nice and minimalist, but ultimately I find I need to do some computation on the prices/sizes and currently that means converting to floating point.

So the end user consumes the data via `Event` where the data are ultimately std::string. Once you have the data as std::string, your custom strategy code can use any library/code to convert those to float or cpp_dec_float or .... :) Does that sound good?
