### ISSUE TITLE
Websocket Subscription Reconnect Mechanism and Database Store

### ISSUE THREAD

**Issue by foonsun** [crypto-chassis/ccapi#129]
An Awesome Project!

Websocket Subscription Reconnect Mechanism and Database Store are needed.

**Comment by cryptochassis** [comment]
> An Awesome Project!
> 
> Websocket Subscription Reconnect Mechanism and Database Store are needed.

Thank you for the recognition. :) For "Websocket Subscription Reconnect Mechanism", the library already has auto reconnect built in on websocket disconnection, let me know if for some situations you observed the auto reconnect doesn't happen as expected. For "Database Store", it was left deliberately as a freedom for the end user. The `Event` class is the data structure that the end user receives and consumers, and it only contains C++ standard library data structures. Once you have `Event`, you can save the data to any backend at your choice. :) If you have a particular backend that needs some assistance or performance optimization, let us know and we'd be happy to jump in. Join us on Discord https://discord.gg/b5EKcp9s8T for instant/private discussions if needed.
