### ISSUE TITLE
Market Order

### ISSUE THREAD

**Issue by efraser123** [crypto-chassis/ccapi#248]
How may I execute a market order, please? A short code snippet would be helpful.
Thanks!

**Comment by cryptochassis** [comment]
In most situations using a limit order is much safer than using a market order. A market order can be simulated by creating a limit order with very large price tolerance. However, I totally understand that there are situations where market orders are needed for one reason or another. With that said, you can use https://github.com/crypto-chassis/ccapi/tree/v5.27.0#complex-request-parameters-1. For example, for binance, it would be
```
Request request(Request::Operation::CREATE_ORDER, "binance", "BTCUSDT");
request.appendParam({
  {"type", "MARKET"},
  {"side", "BUY"},
  {"quantity", "0.0005"},
});
```
