### ISSUE TITLE
PaperTrading with okex seems missing INSTRUMENT_TYPE

### ISSUE THREAD

**Issue by ericyue** [crypto-chassis/ccapi#249]
to reproduce the bug :   set papertrading and exchange=okex.  
It seems there's no code to set INSTRUMENT_TYPE env variable.

**Comment by cryptochassis** [comment]
Very sorry for the late fix. I fixed it in develop branch: https://github.com/crypto-chassis/ccapi/commit/a9921f2b5422cfaab38a3092d1a0bc6daef03dc8, and tested it. Feel free to let me know if it still doesn't work as expected on your end. Apologize again for the late fix. :)

**Comment by cryptochassis** [comment]
Feel free to reopen if you encounter the same issue again.
