### ISSUE TITLE
Paper trading doesn't record private trades

### ISSUE THREAD

**Issue by cryptochassis** [crypto-chassis/ccapi#250]
**Describe the bug**
Paper trading doesn't record private trades

**To Reproduce**
Run paper trading with 0 spread. Unable to see private trades being written to the desired csv file
[log.txt](https://github.com/crypto-chassis/ccapi/files/7885723/log.txt)
. git commit hash is 7094194147ca538733ca2a5845cc48d14b176167

**Comment by ericyue** [comment]
got this problem too

**Comment by cryptochassis** [comment]
Very sorry for the late fix. I fixed it in develop branch: https://github.com/crypto-chassis/ccapi/commit/a9921f2b5422cfaab38a3092d1a0bc6daef03dc8, and tested it. Feel free to let me know if it still doesn't work as expected on your end. Apologize again for the late fix. :)

**Comment by cryptochassis** [comment]
Feel free to reopen if you encounter the same issue again.
