### ISSUE TITLE
spot_market_making alert: "xxxxx floating point exception  ./spot_market_making"

### ISSUE THREAD

**Issue by PIX73** [crypto-chassis/ccapi#272]
**Describe the bug**
After finishing all steps and config, when I enter "./spot_market_making", it shows "xxxxx floating point exception  ./spot_market_making".

**Comment by cryptochassis** [comment]
Let me know whether this can solve your problem or not: https://github.com/crypto-chassis/ccapi/issues/270.

**Comment by itsDreDev** [comment]
Floating-point exceptions also happen when the environment variables are not set.
