### ISSUE TITLE
binance cancel orders not working.

### ISSUE THREAD

**Issue by secwang** [crypto-chassis/ccapi#289]
**Describe the bug**
The first time spot_market_maker will send a cancel orders.
this show error.
**To Reproduce**
use spot market maker. start on binance will show error.

**Expected behavior**
not show error

**Screenshots**
![image](https://user-images.githubusercontent.com/5615339/174478960-69788d76-7e45-43ee-8473-b4e2c76185c2.png)

**Additional context**
Add any other context about the problem here (such as operating system, compiler used, git commit hash used, etc.).

**Comment by secwang** [comment]
No, this is the order just connected. There may be orders on futures, but I'm sure there are no orders on the spot.

**Comment by cryptochassis** [comment]
Right, when you cancel open orders, if binance spot has no orders, binance returns that error, which is spurious.

**Comment by secwang** [comment]
I found this problem, which is quite confusing. Your explanation is for. I'll close this issue first.
