### ISSUE TITLE
Error in setting target for GET_INSTRUMENTS call for Gemini exchange

### ISSUE THREAD

**Issue by rkyleg** [crypto-chassis/ccapi#294]
https://github.com/crypto-chassis/ccapi/blob/b53929e6ad7afab51d2cc3ace70346bdbb64ba6a/include/ccapi_cpp/service/ccapi_market_data_service_gemini.h#L241

the code calls this->getInstrumentTarget for the Request::Operation::GET_INSTRUMENTS case when it should call this->getInstrumentsTarget

**Comment by cryptochassis** [comment]
Thank you for reporting. It was fixed in commit hash 8daad5b444e13cbfc423e4bc3e24296f54b0ac6d.
