### ISSUE TITLE
Order updates on Kraken. Only receiving a pending status update.

### ISSUE THREAD

**Issue by efraser123** [crypto-chassis/ccapi#305]
How may I retrieve order updates on Kraken? I'm subscribing via the line of code below:
Subscription subscription("Kraken", "ETH-USD", "ORDER_UPDATE");
I only receive one update with a STATUS, of "pending" despite orders being completely filled.
Any help would be greatly appreciated.

Thanks
Evan

**Comment by cryptochassis** [comment]
Could you try 
Subscription subscription("Kraken", "ETH/USD", "ORDER_UPDATE");
? Notice that its symbol is "ETH/USD".

**Comment by efraser123** [comment]
Thank you! 
The following worked:
    Request request(Request::Operation::GET_ORDER, "kraken", "ETHUSD");
    request.appendParam({
       {"ORDER_ID", "orderID999"},
    });
//and
 Request request(Request::Operation::GET_OPEN_ORDERS, "kraken", "ETHUSD");
//You must do a:
Subscription subscription("Kraken", "ETH/USD", "ORDER_UPDATE")
// First (only once) to get the pending status and the exchange generated orderID. You could generate a clientOrderId and send it with your order to the exchange to facilitate tracking/lookups in your OMS, Events from the exchange, etc.
The requests above appear to facilitate Kraken's WebSockets authentication token request via REST (https://docs.kraken.com/rest/#tag/Websockets-Authentication. 

Thanks again!
Cheers!
Evan

**Comment by efraser123** [comment]
eg. results 
            nameValueMap = {
              CLIENT_ORDER_ID = 0,
              CUMULATIVE_FILLED_PRICE_TIMES_QUANTITY = 0.000000,
              CUMULATIVE_FILLED_QUANTITY = 0.00000000,
              INSTRUMENT = ETHUSD,
              LIMIT_PRICE = 1763.00,
              ORDER_ID = OMZGLN-XUNM4-QWX6BQ,
              QUANTITY = 0.01000000,
              SIDE = BUY,
              STATUS = canceled
            }
          ]
        ]
    ]
  ]
