### ISSUE TITLE
Assertion `IsArray()' failed on CANCEL_ORDER for BitFinex exchange

### ISSUE THREAD

**Issue by vakakav** [crypto-chassis/ccapi#335]
**Describe the bug**
When sending CANCEL_ORDER request for bitfinex a providing an EventQueue, I get the folowing failed assertion:

`rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]: Assertion `IsArray()' failed.
`

The assertion fails because the function
ExecutionManagementServiceBitfinex::extractOrderInfo assumes that it is called with an array type for argument `const rj::Value& x` but it is called with an individual value for x and calls operator[] on that x.

The cause for this is:
ExecutionManagementServiceBitfinex::extractOrderInfoFromRequest handles CREATE_ORDER and CANCEL_ORDER in the same manner:

```
void extractOrderInfoFromRequest(std::vector<Element>& elementList, const Request& request, const Request::Operation operation, const rj::Document& document) override {
    if (operation == Request::Operation::CREATE_ORDER || operation == Request::Operation::CANCEL_ORDER) {
      Element element;
      this->extractOrderInfo(element, document[4][0]);
      elementList.emplace_back(std::move(element));
    } else if (operation == Request::Operation::GET_ORDER) {
```

But looking at the responses which we receive from bitfinex there is a difference. You can see, that for CREATE_ORDER the 4th entry is an array of arrays, while for CANCEL_ORDER it is just an array.

Response for CREATE_ORDER:
"[1670537236,\"on-req\",null,null,[[109833343300,null,21121987,\"tTESTBTC:TESTUSD\",1670537236127,1670537236127,0.1,0.1,\"EXCHANGE LIMIT\",null,null,null,0,\"ACTIVE\",null,null,1000,0,0,0,null,null,null,0,0,null,null,null,\"API>BFX\",null,null,{}]],null,\"SUCCESS\",\"Submitting 1 orders.\"]"

Response CANCEL_ORDER:
"[1670537288153,\"oc-req\",null,null,[109833343300,null,21121987,\"tTESTBTC:TESTUSD\",1670537236127,1670537236128,0.1,0.1,\"EXCHANGE LIMIT\",null,null,null,0,\"ACTIVE\",null,null,1000,0,0,0,null,null,null,0,0,null,null,null,\"API>BFX\",null,null,{}],null,\"SUCCESS\",\"Submitted for cancellation; waiting for confirmation (ID: 109833343300).\"]"

**To Reproduce**
Almost pseudo code:

ccapi::Request request{ccapi::Request::Operation::CANCEL_ORDER, CCAPI_EXCHANGE_NAME_BITFINEX, "myinstrument")};
request->appendParam({
      {"ORDER_ID", "myorderid"}
});
ccapi::Queue<ccapi::Event> event_queue;
session.sendRequest(request, &event_queue); // <--- assertion fails on this call

**Expected behavior**
Assertion should not fail.

**Additional context**
git commit 077fbf70a187a64581bc0b4fd71e841bf4657930

**Comment by cryptochassis** [comment]
@vakakav I'd appreciate if you could help to fix it and create a pull request. Thank you.

**Comment by cryptochassis** [comment]
@vakakav Thanks a lot for help. I've merged it into develop branch and released it into master branch.

**Comment by vakakav** [comment]
@cryptochassis You're welcome.
