### ISSUE TITLE
Python subscription failure in Huobi

### ISSUE THREAD

**Issue by cpita** [crypto-chassis/ccapi#345]
Using the Python bindings, I am trying to send a GENERIC_PUBLIC_SUSCRIPTION to Huobi but get the following error:

 ERROR_MESSAGE = connection WsConnection [id = 0x7fce6c001b70, url = wss://api.huobi.pro, group = wss://api.huobi.pro|GENERIC_PUBLIC_SUBSCRIPTION|{"sub": "market.btcusdt.bbo", "id": "id1"}, subscriptionList = [ Subscription [exchange = huobi, marginType = , instrumentType = , instrument = , field = GENERIC_PUBLIC_SUBSCRIPTION, optionMap = {}, correlationId = P, credential = {}, serviceName = market_data, timeSent = 2022-12-14T12:12:46.149469200Z] ], credential = {}, status = FAILED, headers = {}] has failed before opening

My code:
```
subscriptionList.append(
  Subscription('huobi',
    '',
    'GENERIC_PUBLIC_SUBSCRIPTION',
    json.dumps({'sub': 'market.btcusdt.bbo',
                'id':'id1'}),
    'P'))
session.subscribe(subscriptionList)
```
I believe this issue arises from the fact that it is trying to connect to wss://api.huobi.pro instead of wss://api.huobi.pro/ws but I am not sure if it is possible to specify a url path with Python.

**Comment by cryptochassis** [comment]
Fixed in https://github.com/crypto-chassis/ccapi/pull/349.
