### ISSUE TITLE
example with visual

### ISSUE THREAD

**Issue by andrewcz** [crypto-chassis/ccapi#385]
@cryptochassis is there a brief example that just streams data and plots the data in real time in a round robin fashion.
cheers,
Andrew

**Comment by cryptochassis** [comment]
What does it mean by plotting data "in a round robin fashion"??

**Comment by andrewcz** [comment]
Plotting only the most recent 100 points @cryptochassis

**Comment by cryptochassis** [comment]
Added a data visualization example: https://github.com/crypto-chassis/ccapi/blob/v6.4.4/binding/python/example/data_visualization/main.py

**Comment by andrewcz** [comment]
cheers @cryptochassis  much appreciated.
