### ISSUE TITLE
ModuleNotFoundError: No module named 'ccapi'

### ISSUE THREAD

**Issue by 111111m** [crypto-chassis/ccapi#386]
I have followed the instruction to build
cmake . -DCMAKE_PROJECT_INCLUDE=user_specified_cmake_include.cmake -DBUILD_VERSION=5.10 -DBUILD_PYTHON=ON -DINSTALL_PYTHON=ON ..

cmake --build .
cmake --install .

Everything was successful. 
Then, I still get this error:     
from ccapi import (Event, EventHandler, Request, Session, SessionConfigs,
ModuleNotFoundError: No module named 'ccapi

How should I solve this?

**Comment by cryptochassis** [comment]
Perhaps try to do it with a venv. i.e. first do `python3 -m venv your-venv-dir`, then do everything above.
