### ISSUE TITLE
segmentation fault, wsConnectionPtr null pointer in onPongByMethod 

### ISSUE THREAD

**Issue by nelyajizi** [crypto-chassis/ccapi#432]
**Describe the bug**
the subscription is working fine but after few seconds, I got a segmentation fault in onPongByMethod while he is trying to use wsConnectionPtr:
this->lastPongTpByMethodByConnectionIdMap[wsConnection.id][method] = timeReceived;
the bug appears with the version v6.4.4, when using the version v5.45.5, there is noticed no issue ..
**To Reproduce**
use 6.4.4:
I subscribed to Kucoin and Ascendex for marketData (depth=5) and trades in addition of sending a request within the same session once every n seconds...
after the subscription started, wait few seconds and the segmentation fault happens..

**Expected behavior**
no issue, receiving event normaly

**Screenshots**

**Additional context**
Add any other context about the problem here (such as operating system, compiler used, git commit hash used, etc.).
![image](https://github.com/crypto-chassis/ccapi/assets/45716874/5aaced84-0190-42c1-b42c-a42d1b0135f9)

**Comment by cryptochassis** [comment]
Yes, I am able to reproduce the bug now.
