### ISSUE TITLE
confusion about postProcessMessageMarketDataEventTrade in event_handler_base.h?

### ISSUE THREAD

**Issue by qcmc17** [crypto-chassis/ccapi#438]
**Describe the bug**
I can not understand why divde then multiple same value in  postProcessMessageMarketDataEventTrade?
`
int intervalStart = UtilTime::getUnixTimestamp(messageTime) / this->adverseSelectionGuardMarketDataSampleIntervalSeconds *
                          this->adverseSelectionGuardMarketDataSampleIntervalSeconds;
`

**Comment by cryptochassis** [comment]
It is integer division: https://stackoverflow.com/questions/3602827/what-is-the-behavior-of-integer-division.
