### ISSUE TITLE
few subscriptions methods fail

### ISSUE THREAD

**Issue by go-dockly** [crypto-chassis/ccapi#456]
I am trying to setup subscriptions:

			subscription = ccapi.NewSubscription(
				exchange,
				symbol,
				"TRADE",
				"CONFLATE_GRACE_PERIOD_MILLISECONDS=40",
				"my correlation id",
			)
			subscription = ccapi.NewSubscription(
				exchange,
				symbol,
				"MARKET_DEPTH",
				"MARKET_DEPTH_MAX=5",
				"my correlation id",
			)

I tested through all of them and everything works fine and well and is amazing.
Only those 2 issues I encountered:
  
  - cryptocom(BTCUSD-PERP):  ERROR_MESSAGE = ws handshake: The WebSocket handshake was declined by the remote peer, category: boost.beast.websocket
(somehow can't connect to this at all)
      
  - kucoin-futures (XBTUSDM): ERROR_MESSAGE = {"id":"0","type":"error","code":400,"data":"topic :XBTUSDM_/contractMarket/level2Depth5 is invalid"}
[docs](https://www.kucoin.com/docs/websocket/futures-trading/public-channels/level2-5-best-ask-bid-orders) indicate the format of the channelID should be something like this but maybe I a interpret the message.data wrongly:

`/contractMarket/level2Depth5:XBTUSDM
`
  - bybit-derivatives (BTCUSDT):           ERROR_MESSAGE = unsupported exchange instrument types: . Allowed values: [ usdt-contract, usdc-contract, usdc-options ].
(here I am a bit puzzled? how do I set the instrument type?)

Thank you very much for this awesome library.

**Comment by cryptochassis** [comment]
Let me try to first address "bybit-derivatives". You'd use `subscription.setInstrumentType("usdt-contract")`. Sorry that I definitely need to put that into the documentation.

**Comment by cryptochassis** [comment]
"kucoin-futures (XBTUSDM)". The error message seems to indicate that there was a typo in the symbol? Should it be `XBTUSDM` rather than `XBTUSDM_`?

**Comment by cryptochassis** [comment]
“cryptocom(BTCUSD-PERP)”: Is your IP address in cryptocom's restricted countries?
