### ISSUE TITLE
support POSITION_UPDATE and POSITION_UPDATE  in okx

### ISSUE THREAD

**Issue by fyr233** [crypto-chassis/ccapi#472]
Hi, I am very grateful for the use of this elegant library. 

I would like to know if there are any plans to further support okx in the near future? 
BALANCE_UPDATE and POSITION_UPDATE subscriptions do not seem to be adapted.
refence API: [https://www.okx.com/docs-v5/en/#trading-account-websocket-balance-and-position-channel](https://www.okx.com/docs-v5/en/#trading-account-websocket-balance-and-position-channel)

**Comment by chassis-community** [comment]
@fyr233 Sorry for the late reply. Yes, we do have a plan to add support for okx for BALANCE_UPDATE and POSITION_UPDATE subscriptions.

**Comment by chassis-community** [comment]
https://github.com/crypto-chassis/ccapi/pull/474

**Comment by chassis-community** [comment]
Released in https://github.com/crypto-chassis/ccapi/releases/tag/v6.8.0. Thank you.
