### ISSUE TITLE
Get account positions via rest api

### ISSUE THREAD

**Issue by cryptochassis** [crypto-chassis/ccapi#84]
**Is your feature request related to a problem? Please describe.**
Getting account positions of derivatives via rest api is important: it allows syncing of information between the exchange and the customer's trading server; it allows algorithms to determine the right action to take knowing the positions.

**Describe the solution you'd like**
Add an operation type of `GET_ACCOUNT_POSITIONS` to class `Request`. Add a type of `GET_ACCOUNT_POSITIONS` to class `Message`. Take bitmex as an example. 

- Modify member function `void convertReq(http::request<http::string_body>& req, const Request& request, const Request::Operation operation, const TimePoint& now, const std::string& symbolId, const std::map<std::string, std::string>& credential)` in `include/ccapi_cpp/service/ccapi_execution_management_service_bitmex.h` so that its `switch` statement can handle `Request::Operation::GET_ACCOUNT_POSITIONS`.  Use member function `appendParam` to handle optional parameter of `ACCOUNT_ID` and `SYMBOL` (i.e. the contract code) for operation `GET_ACCOUNT_POSITIONS`.

- Modify member function `std::vector<Message> convertTextMessageToMessage(const Request& request, const std::string& textMessage, const TimePoint& timeReceived)` in `include/ccapi_cpp/service/ccapi_execution_management_service.h` so that its `switch` statement can handle `Request::Operation::GET_ACCOUNT_POSITIONS` and adds a `Message` to its return. This `Message` will contain one or more `Element`s with each `Element` having a `nameValueMap` with keys: `ACCOUNT_ID` (optional), `SYMBOL` (optional), `POSITION_SIDE` (required), `QUANTITY` (required), `COST` (required).

- Add appropriate unit tests on request conversions and response conversions.

**Comment by BroBan** [comment]
I'm trying to implement the getting of account positions via rest, but i can't find the 'convertReq' function to modify like it says in the description of the issue inside the file 'ccapi_exeuction_management_service.h'. Also i'm guessing this issue doesn't cover implementing the response and requests for each individual exchange, but should rather facilitate a generic implemention, right?

**Comment by cryptochassis** [comment]
@BroBan The problem description "Getting account positions of **derivatives** via rest api is important", so are you implementing it for a derivative exchange (or an exchange with derivative products)? Let me modify the issue details, it was intended for implementing a concrete exchange, but apparent I didn't do a wonderful job in the detailed description...

**Comment by cryptochassis** [comment]
This can be helpful: https://github.com/crypto-chassis/ccapi/blob/26151970d74dd27177b167834a604071eeb22d2c/include/ccapi_cpp/service/ccapi_execution_management_service_coinbase.h
